lpile/lets-hang-be

- db/seeds.rb
- spec/factories/events.rb
- spec/factories/users.rb
* Add one user and 3 events to seed file.
* This PR doesn't close any cards at the moment.
* Nothing at the moment
[Faker gem docs](https://github.com/faker-ruby/faker)
> Create seed file

- app/models/event.rb
- app/models/user.rb
- app/models/user_event.rb
- db/migrate/20190902194326_create_user_events.rb
- db/schema.rb
- db/seeds.rb
- spec/models/event_spec.rb
- spec/models/user_event_spec.rb
- spec/models/user_spec.rb
* Created the UserEvents model
* Set up relationships in User and Event
* Add relationship Specs
* Update seed file
* This PR does not close any cards
* Many to many relationship in Rails
* [Many to Many Relationship Tutorial](https://backend.turing.io/module2/lessons/many_to_many)
> Userevents model

- app/models/user.rb
- db/seeds.rb
- spec/factories/users.rb
* Update seed file
* Add `dependent: :destroy` to User model
* Update user factories
close #6 
> Update Seed File

- app/controllers/static_controller.rb
- public/index.html
* Add landing page controller and template
close #19 
* Figuring out how to add a view to a rails app with --api flag
* [Add homepage to rails api only app](https://stackoverflow.com/questions/38366501/rails-5-api-only-app-with-home-page)
> Add Home Page

- app/models/friendship.rb
- app/models/user.rb
- db/migrate/20190903220609_create_friendships.rb
- db/schema.rb
- db/seeds.rb
- spec/models/friendship_spec.rb
- spec/models/user_spec.rb
* Add Friendships model with spec and migration
* Add friendship relationships to User model with spec
* Update seeds file with friendships
close #1 
* Trying to set up a many to many which references one model.
* [Setting up Friendship Model](https://smartfunnycool.com/friendships-in-activerecord/)
* [Making Friendship rows unique at migration](https://stackoverflow.com/questions/19770888/rails-self-join-scheme-with-has-and-belongs-to-many)
> Add Friendships Model

- app/controllers/api/v1/user/events_controller.rb
- app/models/event.rb
- app/serializers/user_events_serializer.rb
- config/environments/development.rb
- config/routes.rb
- db/migrate/20190904221325_add_event_location_to_events.rb
- db/schema.rb
- spec/factories/events.rb
- spec/models/event_spec.rb
- spec/requests/api/v1/events/index_spec.rb
- spec/requests/api/v1/user/events_index_spec.rb
* Create user events index spec
* Create user events controller with route
* Create user events serializer
Does not close any card as still need to write sad path test and document in README
* Strange error that was resolved with updating a configuration in development environment
> User events index

- README.md
- app/controllers/api/v1/sessions_controller.rb
- config/routes.rb
- spec/requests/api/v1/sessions/create_spec.rb
* Add user login spec
* Add #create action to SessionsController with route
* Add endpoint documentation to README.md
close #8
* [Authentication blog](https://medium.com/@wintermeyer/authentication-from-scratch-with-rails-5-2-92d8676f6836)
> User login

- README.md
- app/controllers/api/v1/events_controller.rb
- app/controllers/api/v1/user/events_controller.rb
- app/serializers/event_serializer.rb
- config/routes.rb
- spec/requests/api/v1/events/create_spec.rb
*Update event controller to include a create
*Add event serializer
*Add event create spec
*Update README
close #4 
*Format datetime
> Events endpoint

- README.md
- app/controllers/api/v1/users_controller.rb
- app/models/user.rb
- config/routes.rb
- spec/requests/api/v1/user/update_spec.rb
* Add user update spec
* Add #create action to UsersController with route
* Remove :password from validates_presence_of in User model for update functionality
* Add edit user endpoints to README.md
close #18 
* [ActiveRecord #create docs](https://guides.rubyonrails.org/active_record_basics.html#create)
> User Update

- README.md
- app/controllers/api/v1/events_controller.rb
- app/controllers/api/v1/user/events_controller.rb
- app/serializers/all_events_serializer.rb
- app/serializers/event_serializer.rb
- app/serializers/user_events_serializer.rb
- config/routes.rb
- db/seeds.rb
- spec/requests/api/v1/events/create_spec.rb
- spec/requests/api/v1/events/index_spec.rb
- spec/requests/api/v1/events/show_spec.rb
- spec/requests/api/v1/user/events_index_spec.rb
* Add events show spec
* Add #show action to EventsController with route
* Add :attendees to EventSerializer
* Add AllEvents serializer
* Refactor events index endpoint to JSON API compliant
close #10
close #30
> Event Show

- README.md
- app/controllers/api/v1/events_controller.rb
- config/routes.rb
- spec/requests/api/v1/events/update_spec.rb
* Add patch event route
* Add update to Events Controller
* Create Event Update spec
close #5 
* Accurate route convention 
* Ensuring we verify the requester is also creator of event and authorized to edit it
> Event update

- app/controllers/api/v1/friendships/request_controller.rb
- app/facades/request_facade.rb
- app/models/friendship.rb
- app/models/user.rb
- app/serializers/request_serializer.rb
- config/routes.rb
- db/migrate/20190907032647_change_confirmed_column_in_friendships.rb
- db/schema.rb
- spec/models/user_spec.rb
- spec/requests/api/v1/friendships/request_spec.rb
* Changed confirmed column to status in Friendship table
* Add instance methods `friend_request`, `accept_request`, and `reject_request` to User model with specs
* Add user can request friend spec
* Add create action to RequestController with route
* Add request facade and serializer for output format
* This PR does not close any cards. 
* How to format the friends relationship to stay RESTful.
> Update Friendship Relationships

- README.md
- app/controllers/api/v1/user/pending_friends_controller.rb
- app/controllers/api/v1/user/requested_friends_controller.rb
- app/serializers/user_events_serializer.rb
- app/serializers/user_pending_friends_serializer.rb
- app/serializers/user_requested_friends_serializer.rb
- config/routes.rb
- db/seeds.rb
- spec/requests/api/v1/user/pending_friends_index_spec.rb
- spec/requests/api/v1/user/requested_friends_index_spec.rb
* Update seed file to be easier to read
* Add user pending friends index spec
* Add PendingFriends with route and serializer
* Add user requested friends index spec
* Add RequestedFriends with route and serializer
* This PR does not close any cards.
* Nothing during this PR.
> Finish friendships

- README.md
- app/serializers/event_serializer.rb
- app/serializers/user_events_serializer.rb
- app/serializers/user_friends_serializer.rb
- db/migrate/20190909233537_change_time_in_events_to_string.rb
- db/schema.rb
- spec/factories/events.rb
- spec/requests/api/v1/events/create_spec.rb
- spec/requests/api/v1/events/show_spec.rb
- spec/requests/api/v1/events/update_spec.rb
- spec/requests/api/v1/user/events_index_spec.rb
- spec/requests/api/v1/user/friends_index_spec.rb
* Change event_time column data type in Event table to string
* This PR does not close any cards.
* [Change column data type](https://tosbourn.com/rails-migrate-change-column-type/)
> Event Time Hotfix

- app/controllers/api/v1/user/event_controller.rb
- app/serializers/event_serializer.rb
- db/seeds.rb
- spec/models/event_spec.rb
- spec/requests/api/v1/user/event_invite_spec.rb
- spec/requests/api/v1/user/user_accepts_event_invite_spec.rb
- spec/requests/api/v1/user/user_declines_event_invite_spec.rb
* Add user can decline event invite
* No cards are close in this PR.
* NOTHING!
> User Can Decline Event Invite

- README.md
- app/controllers/api/v1/users_controller.rb
* Add user.id == params[:id] check to #update action in UsersController
* Add event status endpoints to README.md
* Add friendship status endpoints to README.md
close #
close #
*
* Resource link AND small description of info gathered/learned
> Fix issues

- README.md
- app/controllers/api/v1/user/search_controller.rb
- app/models/user.rb
- app/serializers/friend_search_serializer.rb
- config/routes.rb
- spec/models/user_spec.rb
- spec/requests/api/v1/user/search_friend_spec.rb
* Add user can search for friend if in our data base spec
* Add User::SearchFriendController with routes and Serializer
* Add endpoint to README
* Add case insensitive to user email validation in User model
* This PR does not close any cards at this moment.
* Nothing at this moment
* Resource link AND small description of info gathered/learned
> User Can Search For Friend

- db/seeds.rb
- spec/factories/events.rb
- spec/factories/users.rb
> Update seed file for demo

- Gemfile
- Gemfile.lock
- app/models/message.rb
- config/environments/development.rb
- config/environments/production.rb
- config/initializers/cors.rb
- config/routes.rb
- db/migrate/20191001165336_create_messages.rb
- db/schema.rb
- spec/factories/messages.rb
- spec/models/message_spec.rb
* Add Message model with migration and spec
* Add CORS to project to accept all origins for initial setup
* Config CORS for deployment
* Add messages and cable mount to routes file
* [ActionCable tutorial](https://medium.com/@the.asantiagojr/how-to-setup-actioncable-with-a-rails-api-backend-1f1807c2d908)
> Setup actioncable

- .gitignore
- config/cable.yml
- config/environments/development.rb
- config/environments/production.rb
* Set up redis for heroku deployment
* Corrected cable path
* [Heroku ActionCable Deployment Tutorial](https://blog.heroku.com/real_time_rails_implementing_websockets_in_rails_5_with_action_cable)
> Redis deployment

- db/seeds.rb
* Fix an error within the seeds file
> Correct one error in seed file
